services:
  mariadb:
    restart: unless-stopped
    image: bitnami/mariadb:10.10
    networks:
      - app-tier
    environment:
      MARIADB_USER: ${VZ_DB_USER}
      MARIADB_ROOT_PASSWORD: ${VZ_DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${VZ_DB_PASSWORD}
      MARIADB_DATABASE: ${VZ_DB_DATABASE}
    ports:
      - "${VZ_DB_PORT}:3306"
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
      interval: 5s
      timeout: 5s
      retries: 15

networks:
  app-tier: