version: '3'

tasks:
  docker-image:
    desc: Builds the docker image and tags it
    cmds:
      - gradle clean build
      - docker buildx build --platform linux/amd64,linux/arm64 -t devinfritz/vzbot-discordbot:latest --push .
  start-prod:
    desc: "Start the Docker Compose production environment"
    cmds:
      - docker compose -f docker-compose.yml up -d

  start-dev:
    desc: "Start the Docker Compose development environment"
    cmds:
      - docker compose -f docker-compose.dev.yml up -d

  stop-dev:
    desc: "Start the Docker Compose development environment"
    cmds:
      - docker compose -f docker-compose.dev.yml down

  dev:
    desc: "Build the project with Gradle and boot the Docker Compose dev environment"
    cmds:
      - echo "Building the project using Gradle..."
      - ./gradlew build
      - echo "Starting Docker Compose with development configuration..."
      - docker compose -f docker-compose.dev.yml up -d

  stop:
    desc: "Stop all Docker Compose services"
    cmds:
      - docker compose down
