version: '3'

tasks:
  build-backend:
    desc: Build the backend fat JAR
    dir: backend
    cmds:
      - ./gradlew clean build

  docker-image:
    desc: Builds the backend docker image and pushes it
    cmds:
      - task: build-backend
      - docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/vzbot3d/vzbot-discordbot:latest --push backend/

  start-prod:
    desc: "Start the Docker Compose production environment"
    cmds:
      - docker compose -f docker-compose.yml up -d

  start-dev:
    desc: "Start the Docker Compose development environment"
    cmds:
      - docker compose -f docker-compose.dev.yml up -d

  stop-dev:
    desc: "Stop the Docker Compose development environment"
    cmds:
      - docker compose -f docker-compose.dev.yml down

  dev:
    desc: "Build the backend and start the dev database"
    cmds:
      - echo "Building the backend using Gradle..."
      - task: build-backend
      - echo "Starting Docker Compose with development configuration..."
      - docker compose -f docker-compose.dev.yml up -d

  stop:
    desc: "Stop all Docker Compose services"
    cmds:
      - docker compose down
